
version: '3.3'

services:
  # ngrok:
  #   image: wernight/ngrok
  #   ports:
  #   - "8081:8081"
  #   command:
  #   - /bin/sh
  #   - -c
  #   - |
  #     ngrok start --all
  #   volumes:
  #   - .:/home/ngrok/.ngrok2/
  #   depends_on:
  #   - api-service
  #   - nginx
  
  api-captcha-service:
    build: .
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/hduser/HoangTrongBinh/Captcha_Project/modelDir:/home/node/app/modelDir:rw
      - /home/hduser/HoangTrongBinh/Captcha_Project/datasetDir:/home/node/app/datasetDir:rw
      - /home/hduser/HoangTrongBinh/Captcha_Project/sampleDir:/home/node/app/sampleDir:rw
      - /home/hduser/HoangTrongBinh/Captcha_Project/inferDir:/home/node/app/inferDir:rw
      - /home/hduser/HoangTrongBinh/Captcha_Project/filterDir:/home/node/app/filterDir:rw
    ports:
      - 6790:6790

  mongo:
    image: mongo
    volumes: 
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      
  # nginx:
  #   image: nginx
  #   ports:
  #   - "8080:8080"
  #   volumes:
  #   - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
